"""
Plain Markdown Exporter.
One .md file per conversation, plus a manifest index.
No Obsidian-specific syntax — works anywhere.
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from open_migration.connectors.base import Exporter
from open_migration.graph import KnowledgeGraph, Node


def _safe(title: str, max_len: int = 80) -> str:
    s = re.sub(r'[\\/:*?"<>|]', "", title)
    s = re.sub(r"\s+", "-", s).strip("-")
    return s[:max_len] or "untitled"


def _fmt(iso: str | None) -> str:
    if not iso:
        return ""
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return iso


def _role(role: str) -> str:
    return {
        "user": "**You**", "human": "**You**",
        "assistant": "**AI**", "claude": "**AI**", "model": "**AI**",
        "system": "_System_",
    }.get(str(role).lower(), f"**{str(role).title()}**")


class MarkdownExporter(Exporter):
    name = "markdown"

    def write(self, graph: KnowledgeGraph, output_path: Path) -> None:
        output_path.mkdir(parents=True, exist_ok=True)

        conversations = sorted(
            graph.by_type("conversation"),
            key=lambda n: n.created_at or "",
            reverse=True,
        )

        seen: dict[str, int] = {}
        index_rows: list[str] = []

        for conv in conversations:
            slug = _safe(conv.title or "untitled")
            if slug in seen:
                seen[slug] += 1
                slug = f"{slug}-{seen[slug]}"
            else:
                seen[slug] = 0

            filename = f"{slug}.md"
            messages = graph.children(conv.id, "contains")

            lines = [
                f"# {conv.title or 'Untitled'}",
                "",
                f"- **Source:** {conv.source or 'unknown'}",
            ]
            if conv.created_at:
                lines.append(f"- **Date:** {_fmt(conv.created_at)}")
            lines += [f"- **Messages:** {len(messages)}", ""]
            if conv.url:
                lines += [f"[Original conversation]({conv.url})", ""]
            lines.append("---")
            lines.append("")

            for msg in messages:
                role = msg.metadata.get("role", "unknown")
                time = f" _{_fmt(msg.created_at)}_" if msg.created_at else ""
                lines.append(f"### {_role(role)}{time}")
                lines.append("")
                lines.append((msg.body or "").strip())
                if msg.attachments:
                    lines.append("")
                    lines.append("**Attachments:** " + ", ".join(f"`{a.name}`" for a in msg.attachments))
                lines += ["", "---", ""]

            (output_path / filename).write_text("\n".join(lines), encoding="utf-8")

            date_str = _fmt(conv.created_at)[:10] if conv.created_at else ""
            index_rows.append(
                f"| [{conv.title or 'Untitled'}](./{filename}) "
                f"| {conv.source or '—'} | {date_str} | {len(messages)} |"
            )

        stats = graph.compute_stats()
        index = [
            "# AI Conversation Archive",
            "",
            f"> Generated by [Open Migration](https://github.com/open-migration/open-migration)",
            "",
            "## Stats",
            "",
            f"- **Conversations:** {stats.total_conversations:,}",
            f"- **Messages:** {stats.total_messages:,}",
            f"- **Words:** {stats.total_words:,}",
            f"- **Sources:** {', '.join(stats.sources.keys()) or '—'}",
            "",
            "## Conversations",
            "",
            "| Title | Source | Date | Messages |",
            "|-------|--------|------|----------|",
        ] + index_rows

        (output_path / "README.md").write_text("\n".join(index), encoding="utf-8")
